# Generated by Django 3.0.8 on 2020-08-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('target', 'follower')},
        ),
    ]
