# Generated by Django 3.0.8 on 2020-08-07 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200807_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
